[tool.poetry]
name = "rto-probability"
version = "0.1.0"
description = ""
authors = ["Yass Eltahir <yass.eltahir@coles.com.au>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
plotly = "^5.24.1"
nbformat = ">=4.2.0"
tqdm = "^4.67.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
black = "^24.10.0"
ruff = "^0.9.3"
mypy = "^1.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.coverage.report]
fail_under = 100

[tool.coverage.run]
source = ["src"]

[tool.mypy]
files = ["src/"]
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true


[tool.ruff]
# Use Black-like settings
line-length = 100
indent-width = 4

[tool.ruff.format]
# Use Black-like settings
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.pydocstyle]
convention = "google"